amazon:
    access:
        key: AKIAROLEVK5H434GEE7V
        secret-key: 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
    region: us-east-2
    end-point:
        url: dynamodb.us-east-2.amazonaws.com

server:
    port: 8099